### PR TITLE
peril format test

### PR DESCRIPTION
**Pull request by pieh**

### CODE REVIEW

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
l

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
format

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
blah blah

hokus pokus format

thanks

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by DSchau** [comment]
hokus pokus format

**Comment by pieh** [comment]
test

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
hokus pokus format

**Comment by pieh** [comment]
``` docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Comment by pieh** [comment]
```
docs/sites.yml: SyntaxError: Nested mappings are not allowed in compact mappings (1:10)
 > 1 | - title: ReactJS
     |          ^^^^^^
 > 2 |    main_url: "https://reactjs.org/"
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 > 3 |   url: "https://reactjs.org/"
     | ^
   4 |   source_url: "https://github.com/reactjs/reactjs.org"
   5 |   featured: true
   6 |   categories:
```

**Pull request closed without merging**
